# Generated by Django 6.0.1 on 2026-01-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro.', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación.', verbose_name='Última modificación')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo en el sistema.', verbose_name='Activo')),
                ('tipo', models.CharField(choices=[('SEM', 'Semanal (Vie-Jue)'), ('MEN', 'Mensual (Calendario)')], default='SEM', max_length=3)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('cerrado', models.BooleanField(default=False, help_text='Si está cerrado, no se pueden agregar cobros ni cálculos.', verbose_name='Cerrado')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código identificador')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
