# Generated by Django 6.0.1 on 2026-01-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='cerrado',
            field=models.BooleanField(default=False, verbose_name='Cerrado'),
        ),
    ]
