# Generated by Django 6.0.1 on 2026-02-26 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0006_empresa_casos_nuevos_semana_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('AGENTE', 'Agente de Recobro'), ('CONTABLE', 'Contable'), ('ABOGADO', 'Abogado'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('fecha_alta', models.DateField(auto_now_add=True, null=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('dni_nie', models.CharField(blank=True, max_length=20, null=True)),
                ('netelip_ext', models.CharField(blank=True, max_length=20, null=True)),
                ('mercateli_id', models.CharField(blank=True, max_length=50, null=True)),
                ('contrato_colaboracion', models.FileField(blank=True, null=True, upload_to='contratos_staff/')),
                ('empresas_asignadas', models.ManyToManyField(blank=True, related_name='usuarios_clientes', to='empresas.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
