# Generated by Django 6.0.1 on 2026-02-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='netelip_pass',
            field=models.CharField(blank=True, help_text='Contraseña de Netelip', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='netelip_server',
            field=models.CharField(blank=True, help_text='Servidor SIP de Netelip', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='netelip_user',
            field=models.CharField(blank=True, help_text='Usuario de Netelip (Softphone)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='requiere_cambio_clave',
            field=models.BooleanField(default=True, help_text='Exige al usuario cambiar su clave autogenerada al iniciar sesión por primera vez.'),
        ),
    ]
