# Generated by Django 6.0.1 on 2026-02-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_netelip_pass_perfil_netelip_server_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='clave_temporal',
            field=models.CharField(blank=True, help_text='Almacena la clave generada automáticamente para mostrarla en el detalle.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='netelip_number',
            field=models.CharField(blank=True, help_text='Número telefónico de Netelip', max_length=20, null=True),
        ),
    ]
