# Generated by Django 6.0.1 on 2026-02-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfil_clave_temporal_perfil_netelip_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='mercateli_despacho',
            field=models.CharField(blank=True, help_text='Nombre del despacho en Mercateli', max_length=100, null=True),
        ),
    ]
