# Generated by Django 6.0.1 on 2026-02-27 20:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfil_mercateli_despacho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fecha_alta',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
