# Generated by Django 6.0.1 on 2026-02-02 21:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0007_esquemacomision_alter_empresa_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_cedidos', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_config', to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('numero_expediente', models.CharField(max_length=100, unique=True)),
                ('deudor_nombre', models.CharField(max_length=255)),
                ('deudor_dni', models.CharField(max_length=20)),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_actual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_producto', models.CharField(max_length=50)),
                ('fecha_recepcion', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Con Deuda'), ('PAGADO', 'Deuda Cero'), ('CEDIDO', 'Cedido (SeQura)')], default='ACTIVO', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo_pago', models.CharField(max_length=100)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='pagos/comprobantes/')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='crm.expediente')),
            ],
        ),
    ]
