# Generated by Django 6.0.1 on 2026-02-04 21:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0009_alter_esquemacomision_tipo_caso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_cedidos', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_config', to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_expediente', models.CharField(max_length=100, unique=True)),
                ('deudor_nombre', models.CharField(max_length=255)),
                ('deudor_dni', models.CharField(blank=True, max_length=20, null=True)),
                ('deudor_telefono', models.CharField(max_length=50)),
                ('deudor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tipo_producto', models.CharField(max_length=50)),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_actual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_recuperado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cuotas_totales', models.IntegerField(default=1)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('fecha_impago', models.DateField()),
                ('fecha_recepcion', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Con Deuda'), ('PAGADO', 'Deuda Cero'), ('CEDIDO', 'Cedido'), ('ACUERDO', 'Acuerdo de Pago'), ('INUBICABLE', 'Inubicable')], default='ACTIVO', max_length=20)),
                ('causa_impago', models.CharField(blank=True, choices=[('NO_QUIERE', 'No quiere pagar'), ('CORTA', 'Atiende y corta'), ('AYUDA_FAMILIAR', 'Buscando ayuda familiar'), ('INEXISTENTE', 'Teléfono inexistente'), ('FUERA_SERVICIO', 'Teléfono fuera de servicio'), ('EQUIVOCADO', 'Teléfono equivocado'), ('NO_ATIENDE', 'No atiende'), ('INTENTARA', 'Va a intentar conseguir el dinero'), ('PAGARA', 'Pagará'), ('REEMBOLSADO', 'Reembolsado'), ('SE_REEMBOLSA', 'Se reembolsará'), ('NO_PUEDE', 'No puede pagar'), ('ESPERANDO', 'Esperando respuesta')], max_length=50, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('w1', models.BooleanField(default=False)),
                ('ll1', models.BooleanField(default=False)),
                ('w2', models.BooleanField(default=False)),
                ('ll2', models.BooleanField(default=False)),
                ('w3', models.BooleanField(default=False)),
                ('ll3', models.BooleanField(default=False)),
                ('w4', models.BooleanField(default=False)),
                ('ll4', models.BooleanField(default=False)),
                ('w5', models.BooleanField(default=False)),
                ('ll5', models.BooleanField(default=False)),
                ('buro_enviado', models.BooleanField(default=False)),
                ('buro_recibido', models.BooleanField(default=False)),
                ('asnef_inscrito', models.BooleanField(default=False)),
                ('llamada_seguimiento_asnef', models.BooleanField(default=False)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartera', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo_pago', models.CharField(max_length=100)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='pagos/comprobantes/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='crm.expediente')),
            ],
        ),
    ]
