# Generated by Django 6.0.1 on 2026-02-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='numero_expediente',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
