# Generated by Django 6.0.1 on 2026-02-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_expediente_numero_expediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='deudor_direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_cesion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
