# Generated by Django 6.0.1 on 2026-02-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_expediente_deudor_direccion_expediente_fecha_cesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='fecha_ll1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_ll2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_ll3',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_ll4',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_ll5',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_w1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_w2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_w3',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_w4',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_w5',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
