# Generated by Django 6.0.1 on 2026-02-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_expediente_fecha_ll1_expediente_fecha_ll2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='comentario_estandar',
            field=models.CharField(blank=True, choices=[('SIN_RESPUESTA', 'No tiene respuesta de la academia'), ('ESTAFADO', 'Se siente estafado'), ('SIN_TRABAJO', 'Se encuentra sin trabajo'), ('DESCONOCE', 'No conoce la academia'), ('INCUMPLIMIENTO', 'No cumple el compromiso')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_pago_promesa',
            field=models.DateField(blank=True, null=True),
        ),
    ]
