# Generated by Django 6.0.1 on 2026-02-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_expediente_comentario_estandar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='motivo_eliminacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
