# Generated by Django 6.0.1 on 2026-02-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_expediente_motivo_eliminacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='estado_ll1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='estado_ll2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='estado_ll3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='estado_ll4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='estado_ll5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='estado_w1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='estado_w2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='estado_w3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='estado_w4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='estado_w5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
