# Generated by Django 6.0.1 on 2026-02-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_expediente_estado_ll1_expediente_estado_ll2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='estado_ll1',
            field=models.CharField(blank=True, choices=[('NO_QUIERE', 'No quiere pagar'), ('CORTA', 'Atiende y corta'), ('AYUDA_FAMILIAR', 'Buscando ayuda familiar'), ('INEXISTENTE', 'Teléfono inexistente'), ('FUERA_SERVICIO', 'Teléfono fuera de servicio'), ('EQUIVOCADO', 'Teléfono equivocado'), ('NO_ATIENDE', 'No atiende'), ('INTENTARA', 'Va a intentar conseguir el dinero'), ('PAGARA', 'Pagará'), ('REEMBOLSADO', 'Reembolsado'), ('SE_REEMBOLSA', 'Se reembolsará'), ('NO_PUEDE', 'No puede pagar'), ('ESPERANDO', 'Esperando respuesta')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='estado_ll2',
            field=models.CharField(blank=True, choices=[('NO_QUIERE', 'No quiere pagar'), ('CORTA', 'Atiende y corta'), ('AYUDA_FAMILIAR', 'Buscando ayuda familiar'), ('INEXISTENTE', 'Teléfono inexistente'), ('FUERA_SERVICIO', 'Teléfono fuera de servicio'), ('EQUIVOCADO', 'Teléfono equivocado'), ('NO_ATIENDE', 'No atiende'), ('INTENTARA', 'Va a intentar conseguir el dinero'), ('PAGARA', 'Pagará'), ('REEMBOLSADO', 'Reembolsado'), ('SE_REEMBOLSA', 'Se reembolsará'), ('NO_PUEDE', 'No puede pagar'), ('ESPERANDO', 'Esperando respuesta')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='estado_ll3',
            field=models.CharField(blank=True, choices=[('NO_QUIERE', 'No quiere pagar'), ('CORTA', 'Atiende y corta'), ('AYUDA_FAMILIAR', 'Buscando ayuda familiar'), ('INEXISTENTE', 'Teléfono inexistente'), ('FUERA_SERVICIO', 'Teléfono fuera de servicio'), ('EQUIVOCADO', 'Teléfono equivocado'), ('NO_ATIENDE', 'No atiende'), ('INTENTARA', 'Va a intentar conseguir el dinero'), ('PAGARA', 'Pagará'), ('REEMBOLSADO', 'Reembolsado'), ('SE_REEMBOLSA', 'Se reembolsará'), ('NO_PUEDE', 'No puede pagar'), ('ESPERANDO', 'Esperando respuesta')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='estado_ll4',
            field=models.CharField(blank=True, choices=[('NO_QUIERE', 'No quiere pagar'), ('CORTA', 'Atiende y corta'), ('AYUDA_FAMILIAR', 'Buscando ayuda familiar'), ('INEXISTENTE', 'Teléfono inexistente'), ('FUERA_SERVICIO', 'Teléfono fuera de servicio'), ('EQUIVOCADO', 'Teléfono equivocado'), ('NO_ATIENDE', 'No atiende'), ('INTENTARA', 'Va a intentar conseguir el dinero'), ('PAGARA', 'Pagará'), ('REEMBOLSADO', 'Reembolsado'), ('SE_REEMBOLSA', 'Se reembolsará'), ('NO_PUEDE', 'No puede pagar'), ('ESPERANDO', 'Esperando respuesta')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='estado_ll5',
            field=models.CharField(blank=True, choices=[('NO_QUIERE', 'No quiere pagar'), ('CORTA', 'Atiende y corta'), ('AYUDA_FAMILIAR', 'Buscando ayuda familiar'), ('INEXISTENTE', 'Teléfono inexistente'), ('FUERA_SERVICIO', 'Teléfono fuera de servicio'), ('EQUIVOCADO', 'Teléfono equivocado'), ('NO_ATIENDE', 'No atiende'), ('INTENTARA', 'Va a intentar conseguir el dinero'), ('PAGARA', 'Pagará'), ('REEMBOLSADO', 'Reembolsado'), ('SE_REEMBOLSA', 'Se reembolsará'), ('NO_PUEDE', 'No puede pagar'), ('ESPERANDO', 'Esperando respuesta')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='estado_w1',
            field=models.CharField(blank=True, choices=[('NO_QUIERE', 'No quiere pagar'), ('CORTA', 'Atiende y corta'), ('AYUDA_FAMILIAR', 'Buscando ayuda familiar'), ('INEXISTENTE', 'Teléfono inexistente'), ('FUERA_SERVICIO', 'Teléfono fuera de servicio'), ('EQUIVOCADO', 'Teléfono equivocado'), ('NO_ATIENDE', 'No atiende'), ('INTENTARA', 'Va a intentar conseguir el dinero'), ('PAGARA', 'Pagará'), ('REEMBOLSADO', 'Reembolsado'), ('SE_REEMBOLSA', 'Se reembolsará'), ('NO_PUEDE', 'No puede pagar'), ('ESPERANDO', 'Esperando respuesta')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='estado_w2',
            field=models.CharField(blank=True, choices=[('NO_QUIERE', 'No quiere pagar'), ('CORTA', 'Atiende y corta'), ('AYUDA_FAMILIAR', 'Buscando ayuda familiar'), ('INEXISTENTE', 'Teléfono inexistente'), ('FUERA_SERVICIO', 'Teléfono fuera de servicio'), ('EQUIVOCADO', 'Teléfono equivocado'), ('NO_ATIENDE', 'No atiende'), ('INTENTARA', 'Va a intentar conseguir el dinero'), ('PAGARA', 'Pagará'), ('REEMBOLSADO', 'Reembolsado'), ('SE_REEMBOLSA', 'Se reembolsará'), ('NO_PUEDE', 'No puede pagar'), ('ESPERANDO', 'Esperando respuesta')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='estado_w3',
            field=models.CharField(blank=True, choices=[('NO_QUIERE', 'No quiere pagar'), ('CORTA', 'Atiende y corta'), ('AYUDA_FAMILIAR', 'Buscando ayuda familiar'), ('INEXISTENTE', 'Teléfono inexistente'), ('FUERA_SERVICIO', 'Teléfono fuera de servicio'), ('EQUIVOCADO', 'Teléfono equivocado'), ('NO_ATIENDE', 'No atiende'), ('INTENTARA', 'Va a intentar conseguir el dinero'), ('PAGARA', 'Pagará'), ('REEMBOLSADO', 'Reembolsado'), ('SE_REEMBOLSA', 'Se reembolsará'), ('NO_PUEDE', 'No puede pagar'), ('ESPERANDO', 'Esperando respuesta')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='estado_w4',
            field=models.CharField(blank=True, choices=[('NO_QUIERE', 'No quiere pagar'), ('CORTA', 'Atiende y corta'), ('AYUDA_FAMILIAR', 'Buscando ayuda familiar'), ('INEXISTENTE', 'Teléfono inexistente'), ('FUERA_SERVICIO', 'Teléfono fuera de servicio'), ('EQUIVOCADO', 'Teléfono equivocado'), ('NO_ATIENDE', 'No atiende'), ('INTENTARA', 'Va a intentar conseguir el dinero'), ('PAGARA', 'Pagará'), ('REEMBOLSADO', 'Reembolsado'), ('SE_REEMBOLSA', 'Se reembolsará'), ('NO_PUEDE', 'No puede pagar'), ('ESPERANDO', 'Esperando respuesta')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='estado_w5',
            field=models.CharField(blank=True, choices=[('NO_QUIERE', 'No quiere pagar'), ('CORTA', 'Atiende y corta'), ('AYUDA_FAMILIAR', 'Buscando ayuda familiar'), ('INEXISTENTE', 'Teléfono inexistente'), ('FUERA_SERVICIO', 'Teléfono fuera de servicio'), ('EQUIVOCADO', 'Teléfono equivocado'), ('NO_ATIENDE', 'No atiende'), ('INTENTARA', 'Va a intentar conseguir el dinero'), ('PAGARA', 'Pagará'), ('REEMBOLSADO', 'Reembolsado'), ('SE_REEMBOLSA', 'Se reembolsará'), ('NO_PUEDE', 'No puede pagar'), ('ESPERANDO', 'Esperando respuesta')], max_length=50, null=True),
        ),
    ]
