# Generated by Django 6.0.1 on 2026-02-10 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_expediente_estado_ll1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='crm/pagos/'),
        ),
        migrations.CreateModel(
            name='DocumentoExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONTRATO', 'Contrato de Cesión'), ('OTRO', 'Otra Documentación')], max_length=20)),
                ('archivo', models.FileField(upload_to='crm/documentos/')),
                ('nombre_archivo', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='crm.expediente')),
            ],
        ),
    ]
