# Generated by Django 6.0.1 on 2026-02-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_expediente_comprobante_documentoexpediente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='cuotas_totales',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fecha_impago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
