# Generated by Django 6.0.1 on 2026-02-11 20:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_expediente_cuotas_totales_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registropago',
            options={'ordering': ['-fecha_pago']},
        ),
        migrations.AddField(
            model_name='registropago',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='registropago',
            name='fecha_pago',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='registropago',
            name='metodo_pago',
            field=models.CharField(default='TRANSFERENCIA', max_length=100),
        ),
    ]
