# Generated by Django 6.0.1 on 2026-02-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_registropago_options_registropago_comision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='estado_llamada_seguimiento_asnef',
            field=models.CharField(blank=True, choices=[('NO_QUIERE', 'No quiere pagar'), ('CORTA', 'Atiende y corta'), ('AYUDA_FAMILIAR', 'Buscando ayuda familiar'), ('INEXISTENTE', 'Teléfono inexistente'), ('FUERA_SERVICIO', 'Teléfono fuera de servicio'), ('EQUIVOCADO', 'Teléfono equivocado'), ('NO_ATIENDE', 'No atiende'), ('INTENTARA', 'Va a intentar conseguir el dinero'), ('PAGARA', 'Pagará'), ('REEMBOLSADO', 'Reembolsado'), ('SE_REEMBOLSA', 'Se reembolsará'), ('NO_PUEDE', 'No puede pagar'), ('ESPERANDO', 'Esperando respuesta')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='estado_llamada_seguimiento_buro',
            field=models.CharField(blank=True, choices=[('NO_QUIERE', 'No quiere pagar'), ('CORTA', 'Atiende y corta'), ('AYUDA_FAMILIAR', 'Buscando ayuda familiar'), ('INEXISTENTE', 'Teléfono inexistente'), ('FUERA_SERVICIO', 'Teléfono fuera de servicio'), ('EQUIVOCADO', 'Teléfono equivocado'), ('NO_ATIENDE', 'No atiende'), ('INTENTARA', 'Va a intentar conseguir el dinero'), ('PAGARA', 'Pagará'), ('REEMBOLSADO', 'Reembolsado'), ('SE_REEMBOLSA', 'Se reembolsará'), ('NO_PUEDE', 'No puede pagar'), ('ESPERANDO', 'Esperando respuesta')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_asnef_inscrito',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_buro_enviado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_buro_recibido',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_llamada_seguimiento_asnef',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fecha_llamada_seguimiento_buro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='llamada_seguimiento_buro',
            field=models.BooleanField(default=False),
        ),
    ]
