# Generated by Django 6.0.1 on 2026-02-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_expediente_estado_llamada_seguimiento_asnef_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='tipo_producto',
            field=models.CharField(blank=True, choices=[('TODOS', '--- TODOS LOS PRODUCTOS ---'), ('SEQURA_HOTMART', 'SeQura Hotmart'), ('SEQURA_MANUAL', 'SeQura Manual'), ('SEQURA_COPECART', 'SeQura Copecart'), ('SEQURA_PASS', 'SeQura Pass'), ('AUTO_STRIPE', 'Auto Stripe'), ('AUTOFINANCIACION', 'Autofinanciación')], max_length=50, null=True),
        ),
    ]
