# Generated by Django 6.0.1 on 2026-02-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_expediente_tipo_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropago',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
