# Generated by Django 6.0.1 on 2026-02-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_registropago_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='tipo_producto',
            field=models.CharField(blank=True, choices=[('SEQURA_HOTMART', 'SeQura Hotmart'), ('SEQURA_MANUAL', 'SeQura Manual'), ('SEQURA_COPECART', 'SeQura Copecart'), ('SEQURA_PASS', 'SeQura Pass'), ('AUTO_STRIPE', 'Auto Stripe'), ('AUTOFINANCIACION', 'Autofinanciación'), ('TRANSFERENCIA', 'Transferencia'), ('TODOS', '--- TODOS LOS PRODUCTOS ---')], max_length=50, null=True),
        ),
    ]
