# Generated by Django 6.0.1 on 2026-02-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_alter_expediente_tipo_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropago',
            name='metodo_pago',
            field=models.CharField(choices=[('TRANSFERENCIA', 'Transferencia Bancaria'), ('SEQURA_PASS', 'SeQura Pass'), ('SEQURA_HOTMART', 'Pasarela SeQura Hotmart'), ('SEQURA_MANUAL', 'Pasarela SeQura Manual'), ('SEQURA_COPECART', 'Pasarela SeQura Copecart'), ('STRIPE', 'Stripe (Auto Stripe)'), ('TARJETA', 'Tarjeta de Débito/Crédito')], default='TRANSFERENCIA', max_length=100),
        ),
    ]
