# Generated by Django 6.0.1 on 2026-02-04 21:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('razon_social', models.CharField(max_length=100)),
                ('cif_nif', models.CharField(max_length=20)),
                ('fecha_alta', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('persona_contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=50, null=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('contacto_incidencias', models.CharField(blank=True, max_length=100, null=True)),
                ('email_incidencias', models.EmailField(blank=True, max_length=100, null=True)),
                ('tipos_impagos', models.CharField(blank=True, max_length=255)),
                ('cursos', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('datos_bancarios', models.TextField(blank=True, null=True)),
                ('contrato_colaboracion', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('contrato_cesion', models.FileField(blank=True, null=True, upload_to='contratos/')),
            ],
        ),
        migrations.CreateModel(
            name='EsquemaComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_caso', models.CharField(choices=[('IMPAGO', 'Impago'), ('CEDIDO', 'Cedido')], default='IMPAGO', max_length=20)),
                ('tipo_producto', models.CharField(blank=True, choices=[('TODOS', '--- TODOS LOS PRODUCTOS ---'), ('SEQURA_HOTMART', 'SeQura Hotmart'), ('SEQURA_MANUAL', 'SeQura Manual'), ('SEQURA_COPECART', 'SeQura Copecart'), ('SEQURA_PASS', 'SeQura Pass'), ('AUTO_STRIPE', 'Auto Stripe'), ('AUTOFINANCIACION', 'Autofinanciación')], max_length=50)),
                ('modalidad', models.CharField(choices=[('FIJO', 'Porcentaje Fijo'), ('TRAMOS', 'Escala por Tramos')], default='FIJO', max_length=10)),
                ('porcentaje_fijo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esquemas', to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='TramoComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_minimo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('esquema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos', to='empresas.esquemacomision')),
            ],
        ),
    ]
