# Generated by Django 6.0.1 on 2026-01-21 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro.', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación.', verbose_name='Última modificación')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo en el sistema.', verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre Comercial')),
                ('razon_social', models.CharField(blank=True, max_length=150, verbose_name='Razón Social')),
                ('cif_nif', models.CharField(blank=True, max_length=20, verbose_name='CIF/NIF')),
                ('contacto_incidencias', models.CharField(blank=True, max_length=100, verbose_name='Contacto Incidencias')),
                ('email_incidencias', models.EmailField(blank=True, max_length=254, verbose_name='Email Incidencias')),
                ('datos_bancarios', models.TextField(blank=True, help_text='IBAN, Swift, Banco, etc.', verbose_name='Datos Bancarios')),
                ('tipo_comision', models.CharField(choices=[('FIJA', 'Fija por expediente'), ('VAR', 'Variable (% recuperado)'), ('MIX', 'Mixta (Fija + Variable)')], default='VAR', max_length=4, verbose_name='Tipo de Comisión')),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje base que cobramos por defecto.', max_digits=5, verbose_name='% Comisión Default')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro.', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación.', verbose_name='Última modificación')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo en el sistema.', verbose_name='Activo')),
                ('archivo', models.FileField(upload_to='contratos/', verbose_name='Archivo PDF')),
                ('fecha_firma', models.DateField(blank=True, null=True, verbose_name='Fecha de firma')),
                ('vigente', models.BooleanField(default=True, verbose_name='Vigente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]
