# Generated by Django 6.0.1 on 2026-01-21 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='porcentaje_comision',
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo',
            field=models.CharField(choices=[('SERV', 'Contrato de Prestación de Servicios'), ('CESION', 'Contrato de Cesión de Crédito (ASNEF)')], default='SERV', max_length=10, verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='porcentaje_base',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Usar solo si es Fija o Variable simple.', max_digits=5, verbose_name='% Base / Fijo'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='archivo',
            field=models.FileField(upload_to='contratos/'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='datos_bancarios',
            field=models.TextField(blank=True, verbose_name='Datos Bancarios'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo_comision',
            field=models.CharField(choices=[('FIJA', 'Fija por expediente'), ('VAR', 'Variable (% fijo)'), ('ESC', 'Escalonada (Por volumen mensual)')], default='ESC', max_length=4, verbose_name='Tipo de Comisión'),
        ),
        migrations.CreateModel(
            name='TramoComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_minimo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Mínimo Recobrado')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% Comisión')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Tramo de Comisión',
                'verbose_name_plural': 'Tramos de Comisión',
                'ordering': ['monto_minimo'],
            },
        ),
    ]
