# Generated by Django 6.0.1 on 2026-02-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cif_nif',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
