# Generated by Django 6.0.1 on 2026-01-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_remove_empresa_porcentaje_comision_contrato_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='porcentaje_base',
        ),
        migrations.AddField(
            model_name='empresa',
            name='contrato_cesion',
            field=models.FileField(blank=True, help_text='Requerido para ASNEF/Buró', null=True, upload_to='contratos/cesion/', verbose_name='Contrato de Cesión de Crédito'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='contrato_colaboracion',
            field=models.FileField(blank=True, null=True, upload_to='contratos/colaboracion/', verbose_name='Contrato de Colaboración'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='porcentaje_unico',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Usar solo si el tipo es Porcentaje Fijo.', max_digits=5, null=True, verbose_name='% Único'),
        ),
        migrations.AddField(
            model_name='tramocomision',
            name='monto_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Dejar vacío si es 'en adelante'", max_digits=10, null=True, verbose_name='Hasta (€)'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo_comision',
            field=models.CharField(choices=[('FIJO', 'Porcentaje Fijo Único'), ('TRAMOS', 'Por Tramos (Escalonada)')], default='TRAMOS', max_length=6, verbose_name='Esquema de Comisiones'),
        ),
        migrations.AlterField(
            model_name='tramocomision',
            name='monto_minimo',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Desde (€)'),
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
    ]
