# Generated by Django 6.0.1 on 2026-02-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_empresa_cif_nif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esquemacomision',
            name='tipo_producto',
            field=models.CharField(blank=True, choices=[('TODOS', '--- TODOS LOS PRODUCTOS ---'), ('SEQURA_HOTMART', 'SeQura Hotmart'), ('SEQURA_MANUAL', 'SeQura Manual'), ('SEQURA_COPECART', 'SeQura Copecart'), ('SEQURA_PASS', 'SeQura Pass'), ('AUTO_STRIPE', 'Auto Stripe'), ('AUTOFINANCIACION', 'Autofinanciación'), ('TRANSFERENCIA', 'Transferencia')], max_length=50),
        ),
    ]
