# Generated by Django 6.0.1 on 2026-01-22 20:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_alter_empresa_options_remove_empresa_porcentaje_base_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AddField(
            model_name='empresa',
            name='cursos',
            field=models.TextField(blank=True, help_text='Listado de cursos o productos que vende', verbose_name='Cursos / Productos'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(blank=True, max_length=250, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_alta',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Alta'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Baja'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas Internas'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipos_impagos',
            field=models.TextField(blank=True, help_text='Ej: Tarjeta, Transferencia, Recibo...', verbose_name='Tipos de Impagos'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='contrato_cesion',
            field=models.FileField(blank=True, help_text='Opcional. Requerido para ASNEF/Buró', null=True, upload_to='contratos/cesion/', verbose_name='Contrato de Cesión de Crédito'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='porcentaje_unico',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='% Único'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo_comision',
            field=models.CharField(choices=[('FIJO', 'Porcentaje Fijo Único'), ('TRAMOS', 'Por Tramos (Escalonada)')], default='FIJO', max_length=6, verbose_name='Esquema de Comisiones'),
        ),
        migrations.AlterField(
            model_name='tramocomision',
            name='monto_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hasta (€)'),
        ),
    ]
