# Generated by Django 6.0.1 on 2026-02-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_alter_esquemacomision_tipo_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='costo_buro',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo individual de cada Buró enviado', max_digits=8),
        ),
        migrations.AddField(
            model_name='empresa',
            name='habilita_buro_notificacion',
            field=models.BooleanField(default=False, help_text='Aprobar envío de Buró de Notificación (independiente de cesiones)'),
        ),
        migrations.AlterField(
            model_name='esquemacomision',
            name='tipo_producto',
            field=models.CharField(blank=True, choices=[('SEQURA_HOTMART', 'SeQura Hotmart'), ('SEQURA_MANUAL', 'SeQura Manual'), ('SEQURA_COPECART', 'SeQura Copecart'), ('SEQURA_PASS', 'SeQura Pass'), ('AUTO_STRIPE', 'Auto Stripe'), ('AUTOFINANCIACION', 'Autofinanciación'), ('TRANSFERENCIA', 'Transferencia'), ('TODOS', '--- TODOS LOS PRODUCTOS ---')], max_length=50),
        ),
    ]
