# Generated by Django 6.0.1 on 2026-01-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_alter_empresa_options_empresa_cursos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email General'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='persona_contacto',
            field=models.CharField(blank=True, max_length=100, verbose_name='Persona de Contacto (General)'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='contrato_cesion',
            field=models.FileField(blank=True, null=True, upload_to='contratos/cesion/'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='contrato_colaboracion',
            field=models.FileField(blank=True, null=True, upload_to='contratos/colaboracion/'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cursos',
            field=models.TextField(blank=True, verbose_name='Cursos / Productos'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='porcentaje_unico',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo_comision',
            field=models.CharField(choices=[('FIJO', 'Porcentaje Fijo Único'), ('TRAMOS', 'Por Tramos (Escalonada)')], default='FIJO', max_length=6),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipos_impagos',
            field=models.TextField(blank=True, verbose_name='Tipos de Impagos'),
        ),
    ]
