# Generated by Django 6.0.1 on 2026-02-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_alter_esquemacomision_tipo_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='casos_nuevos_semana',
            field=models.PositiveIntegerField(default=0, help_text='Casos que entraron en impago en los últimos 7 días según el último reporte.'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_ultima_importacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de la última carga masiva.', null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='monto_nuevo_semana',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Suma del monto original de los casos nuevos de la semana.', max_digits=12),
        ),
    ]
