# Generated by Django 6.0.1 on 2026-01-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_empresa_email_contacto_empresa_persona_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono General'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='contrato_colaboracion',
            field=models.FileField(default='contratos/archivo.pdf', upload_to='contratos/colaboracion/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre Comercial'),
        ),
        migrations.AddConstraint(
            model_name='empresa',
            constraint=models.UniqueConstraint(fields=('nombre', 'razon_social'), name='unique_empresa_nombre_razon'),
        ),
    ]
