# Generated by Django 6.0.1 on 2026-01-29 14:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_empresa_telefono_contacto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsquemaComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_caso', models.CharField(choices=[('IMPAGO', 'Gestión de Impago'), ('CEDIDO', 'Cartera Cedida')], default='IMPAGO', max_length=20)),
                ('tipo_producto', models.CharField(blank=True, choices=[('SEQURA_HOTMART', 'SeQura Hotmart'), ('SEQURA_MANUAL', 'SeQura Manual'), ('SEQURA_COPECART', 'SeQura Copecart'), ('SEQURA_PASS', 'SeQura Pass'), ('AUTO_STRIPE', 'Auto Stripe'), ('AUTOFINANCIACION', 'Autofinanciación')], max_length=50, null=True)),
                ('modalidad', models.CharField(choices=[('FIJO', 'Porcentaje Fijo'), ('TRAMOS', 'Escala por Tramos')], default='FIJO', max_length=10)),
                ('porcentaje_fijo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tramocomision',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='empresa',
            name='unique_empresa_nombre_razon',
        ),
        migrations.RemoveField(
            model_name='tramocomision',
            name='empresa',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cif_nif',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='contacto_incidencias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='contrato_cesion',
            field=models.FileField(blank=True, null=True, upload_to='contratos/'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='contrato_colaboracion',
            field=models.FileField(blank=True, null=True, upload_to='contratos/'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cursos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='datos_bancarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email_incidencias',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='fecha_alta',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='persona_contacto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipos_impagos',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tramocomision',
            name='monto_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='tramocomision',
            name='monto_minimo',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tramocomision',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AddField(
            model_name='esquemacomision',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esquemas', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='tramocomision',
            name='esquema',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tramos', to='empresas.esquemacomision'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='porcentaje_unico',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='tipo_comision',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='updated_at',
        ),
    ]
