# Generated by Django 6.0.1 on 2026-02-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_alter_esquemacomision_tipo_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esquemacomision',
            name='tipo_caso',
            field=models.CharField(choices=[('IMPAGO', 'Impago'), ('CEDIDO', 'Cedido')], default='IMPAGO', max_length=20),
        ),
        migrations.AlterField(
            model_name='esquemacomision',
            name='tipo_producto',
            field=models.CharField(blank=True, choices=[('TODOS', '--- TODOS LOS PRODUCTOS ---'), ('SEQURA_HOTMART', 'SeQura Hotmart'), ('SEQURA_MANUAL', 'SeQura Manual'), ('SEQURA_COPECART', 'SeQura Copecart'), ('SEQURA_PASS', 'SeQura Pass'), ('AUTO_STRIPE', 'Auto Stripe'), ('AUTOFINANCIACION', 'Autofinanciación')], max_length=50),
        ),
    ]
